doc-warnings: no
test-warnings: no
strictness: high
max-line-length: 120
uses:
    - django
autodetect: yes
requirements:
    - requirements.txt
ignore-paths:
    - docs

pylint:
 disable:
  - C1001
  - W0612
  - W0613